"""Confirmatory validation of the final outputs. Writes WebScrape/VALIDATION.md.

Checks per institute (main file + unconfirmed file):
  1 schema / required fields / value types            6 todo_fields consistent with TODO values
  2 year in 2016..2026                                 7 verified records: matched affiliation strings re-classified
  3 DOI format, lower-case, unique; main/unconfirmed     8 near-duplicate titles (same normalised title, year ±1)
    overlap; overlap between institutes (joint papers)  9 live re-check of a seeded random sample against Crossref
  4 ISSN format                                           (title, year, venue)
  5 citations non-negative int; references = DOI list  10 citation-count agreement across sources
usage: python3 validate.py iit_ropar iit_kharagpur
"""
import os, re, sys, json, random, collections, html, unicodedata, urllib.parse
from common import OUT, MAILTO, get, norm_doi
from affil import classify

FIELDS = ["title", "authors", "year", "type", "venue", "issn", "doi", "citations", "references"]
TYPES = {"journal", "conference", "book-chapter", "book", "preprint", "thesis", "report", "other", "TODO"}
DOI_RX = re.compile(r"^https://doi\.org/10\.\d{4,9}/\S+$")
ISSN_RX = re.compile(r"^\d{4}-\d{3}[\dX]$")


def istodo(v):
    return isinstance(v, str) and v.startswith("TODO")


def tkey(t):
    t = html.unescape(re.sub(r"<[^>]+>", " ", t or ""))
    t = unicodedata.normalize("NFKD", t).encode("ascii", "ignore").decode().lower()
    return re.sub(r"[^a-z0-9]+", "", t)


def spearman(a, b):
    def rank(x):
        o = sorted(range(len(x)), key=lambda i: x[i]); r = [0] * len(x)
        for k, i in enumerate(o):
            r[i] = k
        return r
    ra, rb = rank(a), rank(b); n = len(a)
    if n < 3:
        return float("nan")
    d2 = sum((x - y) ** 2 for x, y in zip(ra, rb))
    return 1 - 6 * d2 / (n * (n * n - 1))


report = ["# Confirmatory validation report", "", "Generated by `WebScrape/scripts/validate.py`.", ""]
all_dois = {}
for inst in sys.argv[1:]:
    main = json.load(open(os.path.join(OUT, inst + ".json")))
    unc = json.load(open(os.path.join(OUT, f"candidates_unconfirmed_{inst}.json")))["records"]
    R = main["records"]
    issues = collections.Counter(); examples = collections.defaultdict(list)

    def bad(k, r, note=""):
        issues[k] += 1
        if len(examples[k]) < 3:
            examples[k].append(f"{r.get('record_id')} {note}".strip())

    for r in R + unc:
        for f in FIELDS + ["affiliation_status", "evidence", "todo_fields", "record_id"]:
            if f not in r:
                bad("missing_field:" + f, r)
        if not isinstance(r["year"], int) or not (2016 <= r["year"] <= 2026):
            bad("year_out_of_range", r, str(r["year"]))
        if not istodo(r["doi"]) and not DOI_RX.match(r["doi"]):
            bad("doi_format", r, r["doi"])
        if not istodo(r["doi"]) and r["doi"] != r["doi"].lower():
            bad("doi_not_lowercase", r, r["doi"])
        if isinstance(r["issn"], list):
            for x in r["issn"]:
                if not ISSN_RX.match(x):
                    bad("issn_format", r, x)
        elif not (istodo(r["issn"]) or r["issn"].startswith("N/A")):
            bad("issn_value", r, str(r["issn"]))
        if not istodo(r["citations"]) and (not isinstance(r["citations"], int) or r["citations"] < 0):
            bad("citations_value", r, str(r["citations"]))
        if isinstance(r["references"], list):
            if any(not isinstance(x, str) or not x.startswith("10.") for x in r["references"]):
                bad("reference_not_doi", r)
            if not istodo(r["doi"]) and r["doi"][16:] in r["references"]:
                bad("self_reference", r)
        elif not istodo(r["references"]):
            bad("references_value", r)
        if r["type"] not in TYPES:
            bad("type_value", r, r["type"])
        if isinstance(r["authors"], list) and not r["authors"]:
            bad("authors_empty_list", r)
        if not (istodo(r["title"]) or (isinstance(r["title"], str) and r["title"].strip())):
            bad("title_empty", r)
        tf = {f for f in FIELDS if istodo(r[f])} | ({"affiliation"} if r["affiliation_status"] != "verified" else set())
        if tf != set(r["todo_fields"]):
            bad("todo_fields_inconsistent", r, f"{sorted(tf)} vs {r['todo_fields']}")
    # 3 duplicates
    dc = collections.Counter(r["doi"] for r in R if not istodo(r["doi"]))
    for d, n in dc.items():
        if n > 1:
            issues["duplicate_doi_main"] += 1
    mains = {r["doi"] for r in R if not istodo(r["doi"])}
    overlap_unc = sum(1 for r in unc if r["doi"] in mains)
    # 7 verified re-classification
    nver = 0
    for r in R:
        if r["affiliation_status"] == "verified":
            nver += 1
            m = r.get("institute_affiliations_matched") or []
            if not m:
                bad("verified_without_matched_affiliation", r, ",".join(r["evidence"]))
            elif not any(classify(inst, s) == "iit" for s in m):
                bad("verified_affiliation_fails_reclassification", r, m[0][:80])
    # 8 near-duplicate titles
    bt = collections.defaultdict(list)
    for r in R:
        if isinstance(r["title"], str) and len(tkey(r["title"])) > 25:
            bt[tkey(r["title"])].append(r)
    dup_groups = [g for g in bt.values() if len(g) > 1 and max(x["year"] for x in g) - min(x["year"] for x in g) <= 1]
    dup_kinds = collections.Counter(" + ".join(sorted(x["type"] for x in g)) for g in dup_groups)
    # 10 citation agreement
    pairs = [(r["citations_by_source"]["crossref"], r["citations_by_source"]["opencitations"]) for r in R
             if r.get("citations_by_source", {}).get("crossref") is not None and r["citations_by_source"].get("opencitations") is not None]
    pairs_s2 = [(r["citations_by_source"]["crossref"], r["citations_by_source"]["semantic_scholar"]) for r in R
                if r.get("citations_by_source", {}).get("crossref") is not None and r["citations_by_source"].get("semantic_scholar") is not None]
    # 9 live re-check
    rnd = random.Random(7); sample = rnd.sample([r for r in R if not istodo(r["doi"]) and r.get("type_raw") and "10.48550" not in r["doi"]], 200)
    live = collections.Counter(); live_ex = []
    for r in sample:
        d = r["doi"][16:]
        try:
            x = get("https://api.crossref.org/works/" + urllib.parse.quote(d, safe="/()"), params={"mailto": MAILTO})
        except Exception:
            live["fetch_error"] += 1; continue
        if x.status_code != 200:
            live["not_in_crossref_now"] += 1; continue
        it = x.json()["message"]
        y = ((it.get("issued") or {}).get("date-parts") or [[None]])[0][0]
        t_ok = tkey((it.get("title") or [""])[0]) == tkey(r["title"])
        v = (it.get("container-title") or [None])[0]
        v_ok = (not v) or tkey(v) == tkey(r["venue"]) or istodo(r["venue"])
        live["checked"] += 1; live["title_match"] += t_ok; live["year_match"] += (y == r["year"]); live["venue_match"] += v_ok
        if not (t_ok and y == r["year"] and v_ok) and len(live_ex) < 5:
            live_ex.append(f"{r['record_id']} {d}: title_ok={t_ok} year {r['year']}->{y} venue_ok={v_ok}")
        all_dois.setdefault(inst, set())
    all_dois[inst] = mains
    # ---- report
    s = main["summary"]
    report += [f"## {inst}", "",
               f"* records: main {len(R)} (verified {nver}), unconfirmed file {len(unc)}",
               f"* DOI duplicates within main file: {issues.get('duplicate_doi_main', 0)}; main∩unconfirmed DOI overlap: {overlap_unc}",
               f"* near-duplicate titles (same normalised title, year ±1) in main file: {len(dup_groups)} groups — by type: {dict(dup_kinds.most_common(6))}",
               f"* citation agreement Crossref vs OpenCitations: n={len(pairs)}, Spearman ρ={spearman(*zip(*pairs)) if pairs else float('nan'):.3f}, "
               f"median |diff|={sorted(abs(a - b) for a, b in pairs)[len(pairs) // 2] if pairs else 'n/a'}",
               f"* citation agreement Crossref vs Semantic Scholar: n={len(pairs_s2)}, Spearman ρ={spearman(*zip(*pairs_s2)) if len(pairs_s2) > 2 else float('nan'):.3f}",
               f"* live Crossref re-check of 200 random records: {dict(live)}",
               "", "| check | violations | examples |", "|---|---|---|"]
    keys = sorted(set(issues) | {"year_out_of_range", "doi_format", "issn_format", "citations_value", "reference_not_doi", "type_value",
                                 "todo_fields_inconsistent", "verified_affiliation_fails_reclassification", "duplicate_doi_main"})
    report += [f"| {k} | {issues.get(k, 0)} | {'; '.join(examples.get(k, []))} |" for k in keys]
    if live_ex:
        report += ["", "Live re-check mismatches (examples):", ""] + [f"* {e}" for e in live_ex]
    report += [""]
    print(inst, dict(issues), dict(live), len(dup_groups), flush=True)
if len(all_dois) >= 2:
    import itertools
    report += ["## Cross-institute (joint papers present in two main files)", ""]
    for (i1, a), (i2, b) in itertools.combinations(all_dois.items(), 2):
        report += [f"* {i1} ∩ {i2}: {len(a & b)} DOIs"]
    report += [""]
open(os.path.join(OUT, "VALIDATION.md"), "w").write("\n".join(report) + "\n")
print("written VALIDATION.md")
